config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :systems do
        collection do
          post 'measurement'
        end
      end

    end
  end

  resources :salesforce do
    collection do
      get 'salesforce_callback'
    end
  end

  resources :systems
  resources :customers do
    member do
      get :simulate_invoice
      get :create_invoice
      get :component
    end
  end
  resources :products do
    member do
      get :costs
      get :prices
    end
  end
  resources :invoices do
    member do
      get :check
      get :pay
      patch :settle
    end
  end
  root to: 'home#index'
end

app/models/cloud9/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id                :integer          not null, primary key
#  organization_name :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  cloud9_identifier :string(255)
#  billing_frequency :string(255)
#  billing_date_base :date
#

#A CLoud9::Customer is a first class object that has many systems, will manage contact and payment information, will
# be assigned roles to manage some things in the Cloud9 Universe (add a user, for example)
class Cloud9::Customer < ActiveRecord::Base
  include Concerns::Salesforceable

  has_many :systems, :class_name => 'Cloud9::System'
  has_many :components, :class_name => 'Cloud9::Component'
  has_many :invoices, :class_name => 'Cloud9::Invoice'
  has_many :contacts, :class_name => 'Cloud9::Contact', :foreign_key => :cloud9_customer_id
  has_one :salesforce_reference, as: :referenceable

  def self.cloud9_default
    Cloud9::Customer.find_by(
        first_name: Settings.cloud9_customer_first_name,
        last_name: Settings.cloud9_customer_last_name,
        organization_name: Settings.cloud9_customer_organization_name,
        email: Settings.cloud9_customer_email
    )
  end

  #Cloud9 uses an internal identifying system. These tie cloud9 information together through systems. Once the identifier is provided, this method asynch retrieves information from salesForce
  #@params identifier is typically of the form 'rtb####'
  def self.retrieve_by_cloud9_id(identifier)
    cust = Cloud9::Customer.find_or_create_by(cloud9_identifier: identifier)
    if cust.needs_hug_from_sf
      cust.delay.initialize_from_salesforce
    end
    cust
  end

  #Initializes a Saleforce mapping object (Account) and then calls 'find', which retrieves core SalesForce Information. Also retrieves contacts for the customer
  def update_from_salesforce
    acct = Salesforce::Account.new(account_number: self.cloud9_identifier)
    acct.find

    ref = Cloud9::SalesforceReference.new(
        referenceable_id: self.id,
        referenceable_type: self.class.name,
        salesforce_id: acct.salesforce_data.Id,
        salesforce_url: acct.salesforce_data.attributes.url
    )
    self.billing_date_base = acct.salesforce_data.VS_Launch_Date__c
    self.billing_frequency = acct.salesforce_data.Billing_Frequency__c
    self.salesforce_reference = ref
    self.organization_name = acct.salesforce_data.Name
    self.save!

    self.delay.find_contacts_in_salesforce
  end

  #Finding contacts in salesforce is done by first retrieving account information and then submitting a query to SalesForce (encapsulated in acct.find_contacts)
  def find_contacts_in_salesforce
    acct = Salesforce::Account.new(account_number: self.cloud9_identifier)
    contacts = acct.find_contacts
    contacts.each do |contact|
      if contact.Status__c.eql? 'Active'
        c = Cloud9::Contact.create(
          email: contact.Email,
          cloud9_customer_id: self.id,
          name: contact.Name,
          primary: contact.Primary_Contact__c,
          authorized: contact.Authorized_Contact__c
        )

        ref = Cloud9::SalesforceReference.new(
            referenceable_id: c.id,
            referenceable_type: c.class.name,
            salesforce_id: contact.Id,
            salesforce_url: contact.attributes.url
        )
        c.salesforce_reference = ref
        c.save!
      end
    end
  end

  def renewal_pending?
    # Looking for the following two values from salesforce:
    # Billing_Frequency__c (For example, "Annual")
    # VS_Renewal_Date__c (A Date .... for example "2014-12-21")
  end

  def last_sent_invoice
    self.invoices.where(:status => Cloud9::Invoice.status[:sent]).last
  end

  #customers have systems with components, and also some components that are not part of any particular system
  def non_system_components
    non = []
    self.components.each do |comp|
      non << comp if comp.system_id.nil?
    end
    non
  end

  def non_system_product_ids
    non = []
    self.non_system_components.each { |comp| non<<comp.product.id}
    non
  end

  def active_invoices
    self.invoices.order("bill_date DESC").where('workflow_state NOT IN (700,200)')
  end

  def add_non_system_components(product_ids)
    #remove all non_system_components
    non_system_components.each { |comp| comp.delete }

    product_ids.each do |id|
      Cloud9::Component.create(
        product_id: id,
        customer_id: self.id
      )
    end
  end

  def contact_list
    addy = []
    self.contacts.each { |con| addy << con.email unless con.email.blank? }
    addy
  end

end

app/models/customer.rb
class Customer
  # Type stuff here
end

app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < ApplicationController
  respond_to :json

  def index
    render json: Cloud9::Customer.all
  end

  def show
    render json: customer
  end

  def create
    respond_with :api, :v1, Cloud9::Customer.create(customer_params)
  end

  def update
    respond_with product.update(product_params)
  end

  def destroy
    respond_with product.destroy
  end

  private

  def customer
    Cloud9::Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :organization_name, :email, :role, :id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @cloud9_customers = Cloud9::Customer.all
  end

  def show
    @cloud9_customer = customer
    timer = Customer::BillTimer.build(@cloud9_customer, DateTime.now)
    @timer = timer.countdown
  end

  def create
    respond_with :api, :v1, Cloud9::Customer.create(customer_params)
  end

  #The only information that we can update about the customer on this system is products purchased or owned
  def update
    @customer = customer
    @customer.add_non_system_components(customer_params[:components])
    redirect_to customer_path(@customer)
  end

  def destroy
    respond_with product.destroy
  end

  def simulate_invoice
    @cloud9_customer = customer
    sim = Invoicing.new(@cloud9_customer)
    @invoice = sim.sample
  end

  def create_invoice
    @cloud9_customer = customer
    sim = Invoicing.new(@cloud9_customer)
    @invoice = sim.create

    redirect_to customer_path(@cloud9_customer)
  end

  def component
    @cloud9_customer = customer
    @cloud9_products = Cloud9::Product.where("unit_price = false OR unit_price IS NULL")
  end

  private

  def customer
    Cloud9::Customer.find(params[:id])
  end

  def customer_params
    params.require(:cloud9_customer).permit(:first_name, :last_name, :organization_name, :email, :role, :id, :components => [])
  end
end

app/views/customers/_form.html.haml
= form_for @cloud9_customer do |f|
  - if @cloud9_customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cloud9_customer.errors.count, "error")} prohibited this cloud9_customer from being saved:"
      %ul
        - @cloud9_customer.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/customers/component.html.haml
%p#notice= notice

%h3= link_to @cloud9_customer.organization_name, customer_path(@cloud9_customer)


= form_for @cloud9_customer, :url => customer_path do |f|
  - if @cloud9_customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cloud9_customer.errors.count, "error")} prohibited this Customer Information from being saved:"
      %ul
        - @cloud9_customer.errors.full_messages.each do |msg|
          %li= msg

  %table.table-bordered.table-hover
    %tr
      %th= "Type"
      %th= "Product"
      %th= "Include?"
      %th
        = f.submit "Save"
    - prev_name = ''
    - @cloud9_products.each do |cloud9_product|
      %tr
        %td= cloud9_product.product_type.name.capitalize.eql?(prev_name) ? '' : cloud9_product.product_type.name.capitalize
        %td= link_to cloud9_product.invoice_name.capitalize, edit_product_path(cloud9_product)
        - prev_name = cloud9_product.product_type.name.capitalize
        %td
          = check_box_tag "cloud9_customer[components][]",cloud9_product.id, @cloud9_customer.non_system_product_ids.include?(cloud9_product.id)
        %td

app/views/customers/edit.html.haml
%h1 Editing cloud9_customer

= render 'form'

= link_to 'Show', @cloud9_customer
\|
= link_to 'Back', cloud9_customers_path

app/views/customers/index.html.haml
%h1 Listing Customers

%table.table-bordered.table-hover
  %thead
    %tr
      %th Customer
      %th Last Invoice
      
  %tbody
    - @cloud9_customers.each do |cloud9_customer|
      %tr
        %td= link_to cloud9_customer.organization_name, customer_path(cloud9_customer)
        %td TODO

app/views/customers/new.html.haml
%h1 New cloud9_customer

= render 'form'

= link_to 'Back', cloud9_customers_path

app/views/customers/show.html.haml
%p#notice= notice

%h3= "#{@cloud9_customer.organization_name} (#{@cloud9_customer.cloud9_identifier.upcase})"

%table.table-bordered.table-hover
    %tr.success
        %td
            %strong= "Contacts"
        %td
            %strong= "Systems"
        %td
            %strong= "Products"
    %tr
        %td
            %table
                %tr
                    %td
                        %ul
                        - @cloud9_customer.contacts.each do |con|
                            %li= con.display_name
        %td
            %table
                %tr
                    %td
                        %ul
                        - @cloud9_customer.systems.each do |sys|
                            %li=link_to sys.vm, system_path(sys), :class => 'btn btn-mini'
        %td
            %table
                %tr
                    %td
                        %ul
                        - @cloud9_customer.non_system_components.each do |comp|
                            %li= "#{comp.product.name}"
    %tr
        %td
            %table
                %caption= "Invoices"
                %tr
                    %th= "Creation Date"
                    %th= "Bill Date"
                    %th= "Total"
                    %th= "Status"
                - @cloud9_customer.active_invoices.each do |inv|
                    %tr
                        %td
                            = link_to inv.created_at.strftime('%c'), check_invoice_path(inv)
                        %td= inv.bill_date.strftime '%c' unless inv.bill_date.blank?
                        %td= format_pennies(inv[:total])
                        %td= inv.workflow_state_to_s.capitalize
        %td
            %table
                %caption= "Billing Cycle"
                %tr
                    %td= "Cycle: #{@cloud9_customer.billing_frequency}"
                %tr
                    %td= "Start: #{@cloud9_customer.billing_date_base.strftime '%x'}"
                %tr
                    %td= "Next: #{@timer} days"
                %tr
                    %td= link_to "Simulate Invoice", simulate_invoice_customer_path(@cloud9_customer), :class => 'btn btn-small'
                %tr
                    %td= link_to "Create Invoice", create_invoice_customer_path(@cloud9_customer), :class => 'btn btn-small'
        %td
            %table
                %caption= "Manage Add Ons"
                %tr
                    %td= link_to "Add Ons", component_customer_path(@cloud9_customer), :class => 'btn btn-small'

app/views/customers/simulate_invoice.html.haml
%h3= "Simulated Invoice for:"
%h3= link_to @cloud9_customer.organization_name, customer_path(@cloud9_customer)

= render 'invoices/core'