config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :systems do
        collection do
          post 'measurement'
        end
      end

    end
  end

  resources :salesforce do
    collection do
      get 'salesforce_callback'
    end
  end

  resources :systems
  resources :customers do
    member do
      get :simulate_invoice
      get :create_invoice
      get :component
    end
  end
  resources :products do
    member do
      get :costs
      get :prices
    end
  end
  resources :invoices do
    member do
      get :check
      get :pay
      patch :settle
    end
  end
  root to: 'home#index'
end

app/models/cloud9/system.rb
# == Schema Information
#
# Table name: systems
#
#  id                         :integer          not null, primary key
#  virtual_machine_identifier :string(255)
#  raw_data                   :text
#  customer_id                :integer
#  created_at                 :datetime
#  updated_at                 :datetime
#

#Cloud9::Systems are the key operational item for customers and admins to work with. Systems contain components, can
# be built using orders, can be measured, and have users
class Cloud9::System < ActiveRecord::Base

  has_many :components, :class_name => 'Cloud9::Component'
  has_many :measurements, :class_name => 'Cloud9::Measurement'
  belongs_to :customer, :class_name => 'Cloud9::Customer'
  has_and_belongs_to_many :users, :class_name => 'Cloud9::User'

  validates_presence_of :virtual_machine_identifier

  #TODO We need to make sure there are no systems without a customer
  #validates_associated :customer

  after_create :defaults

  def vm
    self.virtual_machine_identifier
  end

  def defaults

    if self.components.blank?
      create_basic_components
    end

  end

  def self.retrieve_by_vm_id(virtual_machine_id, cust_id)
    Cloud9::System.find_or_create_by(virtual_machine_identifier: virtual_machine_id, customer_id: cust_id)
  end

  def active_components
    self.components
  end

  def recent_update
    self.measurements.last.created_at.strftime '%c'
  end

  def create_basic_components
    ['ram', 'cpu', 'hd_boot'].each do |k|
      id = eval("Cloud9::Product.#{k}_id")
      self.components << Cloud9::Component.create(system_id: self.id, product_id: id, customer_id: self.customer_id)
    end
    self.save!
  end


end

app/controllers/api/v1/systems_controller.rb
module Api
  module V1
    class SystemsController < ApplicationController
      include Component
      include System

      skip_before_action :verify_authenticity_token

      def index
        render json: Cloud9::System.all
      end

      def show
        _id = params[:id]
        render json: system(_id)
      end

      def create
        respond_with :api, :v1, Cloud9::System.create(system_params)
      end

      def update
        respond_with system.update(product_params)
      end

      def measurement
        measured_systems = []
        customer = check_customer(system_params)
        @validator = Component::Validating.new
        @yardstick = System::Measuring.new
        params[:system][:measurements].each do |sys|
          system = check_system(sys, customer.id)
          @validator.call(system.id, customer.id, sys)
          measured_systems << @yardstick.call(system,sys)
        end
        render json: measured_systems
      end

      private

      def system_params
        #  virtual_machine_identifier :string(255)
        #  raw_data                   :text
        #  customer_id                :integer
        params.require(:system).permit(
            :id,
            :customer_id,
            :cloud9_id,
            :notes,
            :measurements_attributes  => [:virtual_machine_identifier,
                                          :customer,
                                          :notes,
                                          :ram,
                                          :cpu,
                                          :hd_space,
                                          :users])
      end

      def system(_id)
        Cloud9::System.find(_id)
      end

      def check_customer(sys)
        Cloud9::Customer.retrieve_by_cloud9_id(sys[:cloud9_id])
      end

      def check_system(sys, customer_id)
        Cloud9::System.retrieve_by_vm_id(sys[:virtual_machine_identifier], customer_id)
      end


    end
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  include Component
  include System

  skip_before_action :verify_authenticity_token

  def index
    @cloud9_systems = Cloud9::System.all
  end

  def show
    @cloud9_system = system(params[:id])
  end

  def edit
    @cloud9_system = system(params[:id])
  end

  def create
    respond_with :api, :v1, Cloud9::System.create(system_params)
  end

  def update
    respond_with system.update(product_params)
  end

  def measurement
    measured_systems = []
    customer = check_customer(system_params)
    @validator = Component::Validating.new
    @yardstick = System::Measuring.new
    params[:system][:measurements].each do |sys|
      system = check_system(sys, customer.id)
      @validator.call(system.id, customer.id, sys)
      measured_systems << @yardstick.call(system,sys)
    end
    render json: measured_systems
  end

  private

  def system_params
    #  virtual_machine_identifier :string(255)
    #  raw_data                   :text
    #  customer_id                :integer
    params.require(:system).permit(
        :id,
        :customer_id,
        :cloud9_id,
        :notes,
        :measurements_attributes  => [:virtual_machine_identifier,
                                      :customer,
                                      :notes,
                                      :ram,
                                      :cpu,
                                      :hd_space,
                                      :users])
  end

  def system(_id)
    Cloud9::System.find(_id)
  end

  def check_customer(sys)
    Cloud9::Customer.retrieve_by_cloud9_id(sys[:cloud9_id])
  end

  def check_system(sys, customer_id)
    Cloud9::System.retrieve_by_vm_id(sys[:virtual_machine_identifier], customer_id)
  end


end

app/views/systems/_form.html.haml
= form_for @cloud9_system, :url => system_path do |f|
  - if @cloud9_system.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cloud9_system.errors.count, 'error')} prohibited this cloud9_system from being saved:"
      %ul
        - @cloud9_system.errors.full_messages.each do |msg|
          %li= msg

  %table
    %tr
      %th= "Organization"
      %th= "Contacts"
      %th= "Updated"
      %th= "Components"
    %tr
      %td= link_to @cloud9_system.customer.organization_name, customer_path(@cloud9_system.customer)
      %td
        %table
          - @cloud9_system.customer.contacts.each do |con|
            %tr
              %td= "#{con.name} (#{con.email})"
      %td= @cloud9_system.updated_at
      %td
        %table
          - @cloud9_system.active_components.each do |comp|
            %tr
              %td= "#{comp.product.invoice_name} - #{comp.quantity}"

  -#.actions
  -#  = f.submit 'Save'

app/views/systems/edit.html.haml
%h1
	= "Editing #{@cloud9_system.virtual_machine_identifier}"

= render 'form'

app/views/systems/index.html.haml
%h1 Listing Systems

%table.table-bordered.table-hover
  %thead
    %tr
      %th= "Virtual Machine Name"
      %th= "Measurements"
      %th= "Last Updated"

      
  %tbody
    - @cloud9_systems.each do |cloud9_system|
      %tr
        %td= link_to cloud9_system.vm, system_path(cloud9_system), :class => 'btn btn-mini'
        %td.centered
          = link_to cloud9_system.measurements.count.to_s, system_path(cloud9_system)
        %td= cloud9_system.recent_update

app/views/systems/new.html.haml
%h1 New cloud9_system

= render 'form'

= link_to 'Back', cloud9_systems_path

app/views/systems/show.html.haml
%p#notice= notice

%h3= @cloud9_system.vm.upcase

%table.table-bordered.table-hover
  %tr.success
    %th= "Organization"
    %th= "Measurements"
    %th= "Components"
    %th= "Recent Update"
  %tr
    %td
      %table.table-hover
        %tr.success
          %td= link_to @cloud9_system.customer.organization_name, customer_path(@cloud9_system.customer)
        %tr
          %td
            - @cloud9_system.customer.systems.each do |sys|
              =link_to sys.vm, system_path(sys), :class => 'btn btn-mini' unless sys.id == @cloud9_system.id
    %td
      %table.table-hover
        - @cloud9_system.measurements.each do |mea|
          %tr.success
            %td= "#{mea.creation_date_fmt}: #{mea.ram} | #{mea.cpu} | #{mea.total_hd_space} "
    %td
      %table.table-hover
        - @cloud9_system.active_components.each do |comp|
          %tr.success
            %td= "#{comp.product.invoice_name.capitalize}s - #{comp.quantity}"
    %td= @cloud9_system.recent_update

= link_to 'All Systems', systems_path, :class => 'btn btn-small btn-info'