config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :systems do
        collection do
          post 'measurement'
        end
      end

    end
  end

  resources :salesforce do
    collection do
      get 'salesforce_callback'
    end
  end

  resources :systems
  resources :customers do
    member do
      get :simulate_invoice
      get :create_invoice
      get :component
    end
  end
  resources :products do
    member do
      get :costs
      get :prices
    end
  end
  resources :invoices do
    member do
      get :check
      get :pay
      patch :settle
    end
  end
  root to: 'home#index'
end

app/models/cloud9/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  description         :text
#  invoice_name        :string(255)
#  invoice_description :text
#  product_type_id     :integer
#  active              :boolean
#  created_at          :datetime
#  updated_at          :datetime
#  status              :string(255)
#  notes               :text
#  required_quantity   :integer
#  unit_price          :boolean
#  percentage_price    :boolean
#  contract_percentage :integer
#

#Cloud9::Products can be invoiced against because they have a cost and a price, can be grouped into convenient sets
# (sell a Basic System, not 12 products), and can be associated with a license.
class  Cloud9::Product < ActiveRecord::Base
  include Concerns::Invoiceable

  has_many :product_licenses
  has_many :cost_history, :class => Cloud9::Cost, :dependent => :destroy
  has_many :price_history, :class => Cloud9::Price, :dependent => :destroy
  has_many :costs, :class => Cloud9::Cost, :dependent => :destroy
  has_many :prices, :class => Cloud9::Price, :dependent => :destroy
  belongs_to :product_type
  has_one :cloud9_component, :class_name => 'Cloud9::Component'
  has_and_belongs_to_many :product_groups

  accepts_nested_attributes_for :cost_history
  accepts_nested_attributes_for :price_history

  validates_presence_of :name, :description, :product_type_id

  after_create :defaults

  def defaults
    default_invoice_names
  end

  # Determines the active cost for this product
  def active_cost
    if self.cost_history.length > 0
      i = self.cost_history.find_index { |f| (f.active == true)}
      if i.nil?
        activate_cost(self.cost_history.last)
        i = self.cost_history.find_index { |f| (f.active == true)}
      end
      self.cost_history[i].amount
    else
      0
    end
  end

  # Determines the active price for this product
  def active_price
    if self.price_history.length > 0
      i = self.price_history.find_index { |f| f.active }
      if i.nil?
        activate_price(self.price_history.last)
        i = self.price_history.find_index { |f| f.active }
      end
      self.price_history[i].amount
    else
      0
    end
  end

  def active_price=(val)
    price = Cloud9::Price.create(
        product_id: self.id,
        amount: val
    )
    self.activate_price(price)
  end

  # A simple view of the margin provided by this product
  def margin
    active_price - active_cost
  end

  def activate_cost(cost)
    #set each of the costs
    self.costs.each do |c|
      c.active = false
      c.save
    end

    cost.active = true
    cost.save
    cost
  end

  def activate_price(price)
    #set each of the prices
    self.prices.each do |p|
      p.active = false
      p.save
    end

    price.active = true
    price.save
    price
  end

  def self.active_product_list
    Cloud9::Product.where(active: true)
  end

  def self.ram_id
    unit_pricing("ram", "ram").id
  end

  def self.cpu_id
    unit_pricing("cpu", "cpu").id
  end

  def self.hd_boot_id
    unit_pricing("hard drive","hard drive boot").id
  end

  def self.hd_data_id
    unit_pricing("hard drive","hard drive data").id
  end

  def self.match_component(key)
    map = map_to_component(key)
    map.nil? ? nil : Cloud9::Product.find_by(name: map).id
  end

  private
  def self.unit_pricing(type, unit)
    type = Cloud9::ProductType.find_or_create_by(name: "#{type.downcase}", description: "#{type.downcase}")
    Cloud9::Product.find_or_create_by(
        :product_type_id => type.id,
        :active => true,
        :name => "#{unit.downcase} unit",
        :description => "#{unit.downcase} unit",
        :unit_price => true,
        :status => "production")
  end

  def self.map_to_component(key)
    matching_hash = {"virtual_machine_identifier" => "ignore","notes" => "ignore","ram"  => "ram unit", "cpu"  => "cpu unit","total_hd_space" => "hard drive boot unit","free_hd_space" => "ignore","average_ram_utilization"  => "ignore","pagefile_size" => "ignore", "dataserver" => "ignore","datastore_location"  => "ignore","pagefile_location" => "ignore","total_users" => "vm user"}
    p "MATCH!!!!!!     " +  matching_hash[key]
    matching_hash[key].downcase.eql?("ignore") ? nil : matching_hash[key]
  end

end

app/models/cloud9/product_type.rb
# == Schema Information
#
# Table name: product_types
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  description            :text
#  parent_product_type_id :integer
#  invoice_name           :string(255)
#  invoice_description    :text
#  created_at             :datetime
#  updated_at             :datetime
#

class Cloud9::ProductType < ActiveRecord::Base
  include Concerns::Invoiceable

  has_many :products
  validates_presence_of :name, :description

  after_create :defaults

  def defaults
    default_invoice_names
  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  description         :text
#  invoice_name        :string(255)
#  invoice_description :text
#  product_type_id     :integer
#  active              :boolean
#  created_at          :datetime
#  updated_at          :datetime
#

class  Product < ActiveRecord::Base
  include Concerns::Invoiceable

  has_many :requirements, as: :requireable
  has_many :product_licenses
  has_many :product_costs
  has_many :product_prices
  belongs_to :product_type
  has_and_belongs_to_many :product_groups
  has_and_belongs_to_many :orders

  validates_presence_of :name, :description

  after_create :defaults

  def defaults
    default_invoice_names
  end

  # Determines the active cost for this product
  def cost
    if self.product_costs.length > 0
      i = self.product_costs.find_index { |f| (f.active == true)}
      self.product_costs[i].cost
    else
      0
    end
  end

  # Determines the active price for this product
  def price
    if self.product_prices.length > 0
      i = self.product_prices.find_index { |f| (f.active == true)}
      self.product_prices[i].price
    else
      0
    end
  end

  # A simple view of the margin provided by this product
  def margin
    price - cost
  end

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  include Concerns::Invoiceable
  after_create :defaults

  def defaults
    default_invoice_names
  end


end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  respond_to :json

  def index
    render json: Cloud9::Product.all
  end

  def show
    render json: product
  end

  def create
    respond_with Cloud9::Product.create(product_params)
  end

  def update
    respond_with product.update(product_params)
  end

  def destroy
    respond_with product.destroy
  end

  private

  def product
    Cloud9::Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :active, :description, :notes, :status, :invoice_name,
                                    :invoice_description, :product_type_id, :required_quantity,:unit_price)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @cloud9_products = Cloud9::Product.all
  end

  def edit
    @cloud9_product = product
  end

  def create
    respond_with Cloud9::Product.create(product_params)
  end

  def update
    redirect_to products_path if product.update(product_params)
  end

  def destroy
    respond_with product.destroy
  end

  def prices
    @cloud9_product = product

  end

  private

  def product
    Cloud9::Product.find(params[:id])
  end

  def product_params
    params.require(:cloud9_product).permit(:name, :active, :description, :notes, :status, :invoice_name,:invoice_description, :product_type_id, :required_quantity, :unit_price,:active_price)
  end

end

app/views/products/_form.html.haml
= form_for @cloud9_product, :url => product_path do |f|
  - if @cloud9_product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cloud9_product.errors.count, "error")} prohibited this cloud9_product from being saved:"
      %ul
        - @cloud9_product.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %table
      %tr
        %td
          %table.table-bordered.table-hover
            %tr
              %td= "Name:"
              %td
                =f.text_field :name, :required => true
            %tr
              %td= "Description:"
              %td
                =f.text_area :description, :required => true
            %tr
              %td= "Invoice Name:"
              %td
                =f.text_field :invoice_name
            %tr
              %td= "Invoice Description:"
              %td
                =f.text_area :invoice_description
        %td
          %table.table-bordered.table-hover
            %tr
              %td= "Type"
              %td
                = select_tag "cloud9_product[product_type_id]", options_for_select(Cloud9::ProductType.all.map { |prod| [prod.name.capitalize, prod.id] }, @cloud9_product.product_type_id)
            %tr
              %td= "Status"
              %td
                = select_tag "cloud9_product[status]", options_for_select(['new', 'production', 'staged', 'closed', 'bad'], @cloud9_product.status)
            %tr
              %td= "Active Price"
              %td= link_to format_pennies(@cloud9_product.active_price), prices_product_path(@cloud9_product), :class => 'btn btn-mini'
            %tr
              %td= "Active Cost"
              -#%td= link_to format_pennies(@cloud9_product.active_cost), costs_product_path(@cloud9_product), :class => 'btn btn-mini'
              %td= "TODO"


  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1
	= "Editing #{@cloud9_product.invoice_name.capitalize}"

= render 'form'
= link_to 'All Products', products_path

app/views/products/index.html.haml
%h1 Products Listing

%table.table-bordered.table-hover
  %thead
    %tr
      %th Type
      %th Product
      %th Delete?
      
  %tbody
    - prev_name = ''
    - @cloud9_products.each do |cloud9_product|
      %tr
        %td= cloud9_product.product_type.name.capitalize.eql?(prev_name) ? '' : cloud9_product.product_type.name.capitalize
        %td= link_to cloud9_product.invoice_name.capitalize, edit_product_path(cloud9_product)
        %td= link_to 'Remove', product_path(cloud9_product), :method => :delete, :class => 'btn btn-danger btn-mini',:data => { :confirm => 'Are you sure?' }
      - prev_name = cloud9_product.product_type.name.capitalize

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New cloud9_product

= render 'form'

= link_to 'Back', cloud9_products_path

app/views/products/prices.html.haml
%h1
  = "Editing Prices: #{@cloud9_product.invoice_name.capitalize}"

= form_for @cloud9_product, :url => product_path do |f|
  - if @cloud9_product.errors.any?
    #error_explanation
    %h2= "#{pluralize(@cloud9_product.errors.count, "error")} prohibited this cloud9_product from being saved:"
    %ul
      - @cloud9_product.errors.full_messages.each do |msg|
        %li= msg

  %fieldset
    %table.table-bordered
      %tr
        %th= "Add Price (in $0.01; 1000 = $10.00)"
        %th
      %tr
        %td
          = f.text_field :active_price
          %br
          = f.submit "Update", :class => 'btn btn-small btn-success'
        %td
      %tr
        %th= "Historical Prices"
      %tr
        %td
          %table
            %tr
              %th= "Amt"
              %th= "Effective Date"
            - @cloud9_product.prices.order("created_at DESC").each do |p|
              %tr
                %td= "#{format_pennies(p.amount)}"
                %td= "#{p.created_at.strftime '%c'}"

app/views/products/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_product_path(@cloud9_product)
\|
= link_to 'Back', cloud9_products_path