config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :systems do
        collection do
          post 'measurement'
        end
      end

    end
  end

  resources :salesforce do
    collection do
      get 'salesforce_callback'
    end
  end

  resources :systems
  resources :customers do
    member do
      get :simulate_invoice
      get :create_invoice
      get :component
    end
  end
  resources :products do
    member do
      get :costs
      get :prices
    end
  end
  resources :invoices do
    member do
      get :check
      get :pay
      patch :settle
    end
  end
  root to: 'home#index'
end

app/views/layouts/_messages.html.haml
.top-message
  - flash.each do |name, msg|
    - if msg.is_a?(String) and name.is_a?(String)
      / Used for setting messages
      %div{class: "alert alert-block fade in alert-#{name == 'notice' ? "success" : name == 'warning' ? "" : "danger"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, msg, :id => "flash_#{name}"
    - elsif msg.is_a?(String)
      %div{class: "alert alert-#{name == :notice ? "success" : name == :warning ? "" : "danger"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloud9Core</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Cloud9 Automation</a>
    <ul class="nav">
      <li><%=link_to 'Products', products_path %></li>
      <li><%=link_to 'Customers', customers_path %></li>
      <li><%=link_to 'Systems', systems_path %></li>
    </ul>

  </div>
</div>

<%= yield %>

<!--<div id="ember-app"></div>-->

</body>
</html>